### ISSUE TITLE
I get this error call when try to open app

### ISSUE THREAD

**Issue by milos5593** [mjmlio/mjml-app#204]
TypeError: Expected Array or iterable object of values: [object Object]
    at z (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:17612)
    at A (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:16904)
    at r (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:15438)
    at Ue (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:25243)
    at e (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:519849)
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:229550
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14071
    at Array.reduce (<anonymous>)
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14043
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:13812
    at e (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414008)
    at p (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:176241)
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:442693
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:518810
    at file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:522149
    at e (file:///C:/Users/mvuji/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414897)

**Comment by meriadec** [comment]
see https://github.com/mjmlio/mjml-app/issues/188

**Comment by milos5593** [comment]
@meriadec That solution is for Mac I am using Win 10.

**Comment by ngarnier** [comment]
The solution is the same on Windows, except that the path to find the file will be slightly different (as it's Windows): something like `C:\Users\<username>\AppData`. It might be hidden directory.
