### ISSUE TITLE
Error after email sending

### ISSUE THREAD

**Issue by alexandr-bas** [mjmlio/mjml-app#205]
Hello! I've tried to send email via mailjet (in desktop app) and then blank screen appeared.

After app restarting there only error message displayed and nothing happens next.

![image](https://user-images.githubusercontent.com/36625531/36385589-f464559a-15a3-11e8-825f-517ba9e95e9f.png)

TypeError: Expected Array or iterable object of values: [object Object]
    at z (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:17612)
    at A (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:16904)
    at r (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:15438)
    at Ue (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:25243)
    at e (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:519849)
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:229550
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14071
    at Array.reduce (<anonymous>)
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14043
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:13812
    at e (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414008)
    at p (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:176241)
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:442693
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:518810
    at file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:522149
    at e (file:///C:/Users/a.basyukov/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414897)

Windows 10 x64

After trying 2.6.0 version (uninstall 2.7.0 and install 2.6.0) nothing changed

**Comment by alexandr-bas** [comment]
UPDATE: registry cleanup and re-installation helped.

**Comment by divyeshmakwana96** [comment]
@alexandr-bas I created a utility which works with MJML files to send test emails.
https://github.com/divyeshmakwana96/Pochta
