### ISSUE TITLE
error at ini

### ISSUE THREAD

**Issue by lucasandaurus** [mjmlio/mjml-app#207]
Hi all:
 Let me show you an error after update mjml to 3.10 version.
Does anybody know what can I do?

```
TypeError: Expected Array or iterable object of values: [object Object]
    at z (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:17612)
    at A (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:16904)
    at r (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:15438)
    at Ue (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:25243)
    at e (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:519849)
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:229550
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14071
    at Array.reduce (<anonymous>)
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:14043
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:58:13812
    at e (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414008)
    at p (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:35:176241)
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:442693
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:518810
    at file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:64:522149
    at e (file:///C:/Users/lucas.andreoni/AppData/Local/Programs/mjml-app/resources/app.asar/dist/bundle.js:42:414897)
```

This is my screen
![imagen](https://user-images.githubusercontent.com/36709307/36675188-132cdea0-1ae7-11e8-8e43-fc7667e4dff3.png)

Hope you can help.

Thanks!

**Comment by meriadec** [comment]
v2.7.0 leads to *many* problems of that type. Didn't had time to investigate on the "why".
I just removed the 2.7.0 release, you may want to downgrade to 2.6.0 to fix your problem: https://github.com/mjmlio/mjml-app/releases/tag/2.6.0

**Comment by lucasandaurus** [comment]
Thanks @meriadec ,  I had tryed to downgrade to 2.6.0 from console and it turns back this message:
![imagen](https://user-images.githubusercontent.com/36709307/36678550-d699e592-1aef-11e8-9cf5-8af2e4713bb0.png)
Does It means I should only download the excecutable from the url before I could install the 2.6.0 version?

**Comment by meriadec** [comment]
Yeah, mjml-app is not on the npm registry. Release are pushed to github directly. You can either download from url given, or compile it from source (see README.md). Have a good day ! :)
