### ISSUE TITLE
Made a layout, and now Ooops....

### ISSUE THREAD

**Issue by vicmunez85** [mjmlio/mjml-app#239]
I made a couple layouts in the MJML App, and when I try to open it, I get this:
Not really sure what that means, but had to remake the layouts:
Just reporting it

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\MJML\resources\app.asar\node_modules\query-string\index.js:147:36
    at Array.forEach (<anonymous>)
    at exports.parse (C:\Program Files\MJML\resources\app.asar\node_modules\query-string\index.js:138:17)
    at decodeQuery (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useQueries.js:45:52)
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useQueries.js:75:25
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useBasename.js:67:16
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:55:14
    at Array.forEach (<anonymous>)
    at updateLocation (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:54:15)
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:119:56
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:90:9
    at next (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\AsyncUtils.js:51:7)
    at loopAsync (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\AsyncUtils.js:55:3)
    at confirmTransitionTo (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:80:31)
    at transitionTo (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:100:5)
```

**Comment by meriadec** [comment]
Hey. I liked your issue title.

Given the error you pasted, something went wrong when transitioning to a new page. In the app, we internally use the project name in the url for routing to project page. Apparently, there is a problem parsing the project name you used.

Can you try renaming the project?

**Comment by iRyusa** [comment]
Looks like https://github.com/mjmlio/mjml/issues/1020 to me ?

**Comment by vicmunez85** [comment]
So had to delete the old templates I had made, and rebuild them. I believe it had to do with some characters in the project name. Definitely had a "%" in there.

All is well in the world!
