### ISSUE TITLE
Can't open projects or create files with plus or ampersand character(s) in the path

### ISSUE THREAD

**Issue by outdooracorn** [mjmlio/mjml-app#306]
### Describe the bug
When creating or opening a project that contains a "special" character nothing is shown. Trying to create a new file in the project displays the error: `Error creating file`. The interesting thing is that it is able to create the project folder with a special character in the path, just not open it. I had a plus (+) character in the path and it looks like issue #225 had the same problem with an ampersand (&) character. I say "special" as plus (+) and ampersand (&) don't work but other special characters, e.g. a dash (-), do. These are both valid characters in a path on Linux, Windows and OSX.

The developer console shows this error which seems pertinent:
```
index.html#/project?path=D:\SB\Swanbarton Limited\SB - 2755 IFBF 2020\Website + Eventbee\Custom Order Emails\IFBF 2020 MJML Templates:
1 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir 'D:\SB\Swanbarton Limited\SB - 2755 IFBF 2020\Website   Eventbee\Custom Order Emails\IFBF 2020 MJML Templates'
```
It shows that the plus (+) character has been replaces with a space which of cause results in a `no such file or directory` error.

### To Reproduce
1. Open MJML App on Windows 10
2. Click on 'New project'
3. Enter a project name with a special character (e.g. "Test+Project")
4. Click on 'Choose template'
5. Click on 'Create'
6. See app with no contents
7. Click on 'New file'
8. Enter a new file name (e.g. "newfile")
9. Click on 'Create file'
10. See error `Error creating file`
11. Click on 'View -> Toggle Developer Tools'
12. Click on the 'Console' tab
13. See error beginning with `Uncaught (in promise) Error: ENOENT: no such file or directory,`

### Expected behavior
As a new user, I expected to see some content when creating a new project, not a blank area. When I create a new file I expect the file to be created, not a nondescript error.

### Screenshots
![image](https://user-images.githubusercontent.com/43674967/69736565-ad2e1b00-112a-11ea-964a-da567dd8c837.png)
![image](https://user-images.githubusercontent.com/43674967/69736723-f8e0c480-112a-11ea-84e3-ff89f2a69c67.png)

### Environment
 - **OS**: Windows 10 
   - **Version**: 1809 
   - **OS Build**: 17763.864
 - **App Version**: v2.12.0

**Comment by outdooracorn** [comment]
A quick test (on Windows) shows that grave (`) exclamation mark (!), pound (£), dollar ($), caret (^) open bracket ((), close bracket ()), dash (-), underscore (_), open curly bracket ({), close curly bracket (}), open square bracket ([), close square bracket (]), tilde (~), at (@), semi-colon (;), comma (,) and full stop (.) all work when creating a project.

Hash (#) behaves the same as plus (+) and ampersand (&) in that it creates the project but can't open it.

Percent (%) pops up the following error and fails to create the project:
```URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\MJML\resources\app.asar\node_modules\query-string\index.js:147:36
    at Array.forEach (<anonymous>)
    at exports.parse (C:\Program Files\MJML\resources\app.asar\node_modules\query-string\index.js:138:17)
    at decodeQuery (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useQueries.js:45:52)
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useQueries.js:75:25
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\useBasename.js:67:16
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:55:14
    at Array.forEach (<anonymous>)
    at updateLocation (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:54:15)
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:119:56
    at C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:90:9
    at next (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\AsyncUtils.js:51:7)
    at loopAsync (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\AsyncUtils.js:55:3)
    at confirmTransitionTo (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:80:31)
    at transitionTo (C:\Program Files\MJML\resources\app.asar\node_modules\history\lib\createHistory.js:100:5)
```

Colon (:), question mark (?) and asterisk (*) show the error `ENOENT No such file or directory, mkdir <filepath>` as you would probably expect given that they are [reserved characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)

**Comment by benjamin74** [comment]
Percent sign "%" is not working on Mac OSX as Project Name

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/query-string/index.js:147:36
    at Array.forEach (<anonymous>)
    at exports.parse (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/query-string/index.js:138:17)
    at decodeQuery (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/useQueries.js:45:52)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/useQueries.js:75:25
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/useBasename.js:67:16
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:55:14
    at Array.forEach (<anonymous>)
    at updateLocation (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:54:15)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:119:56
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:90:9
    at next (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/AsyncUtils.js:51:7)
    at loopAsync (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/AsyncUtils.js:55:3)
    at confirmTransitionTo (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:80:31)
    at transitionTo (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/history/lib/createHistory.js:100:5)

**Comment by kmcb777** [comment]
should be fixed by https://github.com/mjmlio/mjml-app/pull/363, the release will come soon
