### ISSUE TITLE
Can't install from source anymore

### ISSUE THREAD

**Issue by Komatik** [mjmlio/mjml-app#387]
I could be wrong but it seems that mjml-app is no longer up to date.
Installed it with both Yarn and NPM nothing works. 
(Running Node v18.12.1)     
    
    
    
> **yarn install v1.22.19**

```
[1/4] Resolving packages...
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.1.0"
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.4.3"
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.4.1"
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.4.0"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
[4/4] Building fresh packages...
[1/3] ⠠ electron
[-/3] ⠠ waiting...
error C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\RANDOM_APP_USER\\Desktop\\mjapp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@18.12.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python311\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python311\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:412:12)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RANDOM_APP_USER\\Desktop\\mjapp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\RANDOM_APP_USER\Desktop\mjapp\node_modules\node-sass
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by vanderSangen88** [comment]
Not able to open the installed .dmg either
![Screenshot 2023-01-11 at 09 53 04](https://user-images.githubusercontent.com/16005393/211761734-dcd6df86-f433-4a20-b885-667dc533b9a4.png)

**Comment by iRyusa** [comment]
The error message state you're missing Python in your Path so it could compile node sass.

And for @vanderSangen88 you can open "unverified app" on OSX.

**Comment by Komatik** [comment]
It requires Python 2, which is deprecated and windows won't let you install it either
Am running python 3 though and it doesn't work either.

Not sure what the workaround is ?

![image](https://user-images.githubusercontent.com/3177509/218069289-86def0d5-07cf-46bb-8213-c25fc30c6e3f.png)

**Comment by iRyusa** [comment]
Python 2 doesn't mean python 2.0. Any 2.X  version in your Path will do the trick. I'm not really a windows User so i'm can't really help you here
